name: "Exemplo Logs"
run-name: "Pipeline (Exemplo Logs) executado por ${{github.actor}}"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Adicionando mensagens de log
        run: |
          echo "::debug:: Mensagem de log (debug1)"
          echo "::debug:: Mensagem de log (debug2)"
          echo "::debug:: Mensagem de log (debug3)"
          echo "::notice:: Mensagem de log (notice)"
          echo "::warning:: Mensagem de log (warning)"
          echo "::error:: Mensagem de log (error)"
      - name: Agrupamento de log
        run: |
          echo "::group:: Grupo de logs"
          echo "info 1"
          echo "::warning:: Mensagem de log 1(warning)"
          echo "::warning:: Mensagem de log 2(warning)"
          echo "info 2"
          echo "info 3"
          echo "::endgroup::"
